[build]
  publish = "build"
  command = "CI=false npm run build"

[build.environment]
  REACT_APP_API_URL = "https://jobboard-7q35.onrender.com"
  REACT_APP_ENV = "production"

# Redirects for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"