type QuestionCategories = "Experience" | "Background" | "Skills" | "Culture";

export const fullQuestionPool: Record<QuestionCategories, string[]> = {
  Experience: [
    "What makes you a good fit for this position?",
    "Describe your most relevant work experience.",
    "What are your salary expectations?",
    "What was your biggest professional achievement?",
    "How do you handle challenging workplace situations?",
    "What is your management style?",
    "Describe a successful project you led",
    "How do you prioritize your work?",
    "What are your career goals for the next 5 years?",
    "How do you stay updated in your field?",
  ],
  Background: [
    "Are you legally authorized to work in the United States?",
    "Have you previously worked for our company?",
    "When can you start?",
    "What is your highest level of education?",
    "Do you have any professional certifications?",
    "Have you worked in similar industries before?",
    "What languages do you speak?",
    "Are you willing to relocate?",
    "Can you work overtime if needed?",
    "Do you have any security clearances?",
  ],
  Skills: [
    "Do you have experience with required technical skills?",
    "What is your proficiency level in relevant software?",
    "List any relevant certifications you hold.",
    "Rate your problem-solving abilities",
    "How comfortable are you with new technologies?",
    "Describe your experience with team collaboration tools",
    "What programming languages are you proficient in?",
    "How do you approach learning new skills?",
    "What is your experience with project management?",
    "Describe your analytical capabilities",
  ],
  Culture: [
    "How do you contribute to team culture?",
    "What type of work environment do you prefer?",
    "How do you handle workplace conflicts?",
    "What motivates you at work?",
    "How do you maintain work-life balance?",
    "What are your core professional values?",
    "How do you handle feedback?",
    "Describe your ideal company culture",
    "How do you collaborate with diverse teams?",
    "What makes a great workplace for you?",
  ],
};
