export interface Job {
    id: number,
      title: string,
      status?: string,
      company: string,
      location: string,
      address: string,
      city: string,
      state: string,
      minWage: number,
      maxWage: number,
      type: string,
      industry: string,
      description: string,
      requirements?: string[],
      skills: string[],
      logo: string,
      benefits?: string[],
      tags?: string[],
      schedule?: string[],
      applyWebsite?: string,
      startDate?: string,
      employerId: number
}